default:
  image:
    name: node:22
  tags:
    - docker
  cache:
    key: $CI_COMMIT_REF_SLUG
    policy: pull-push
    paths:
      - .yarn/

variables:
  BIBAPI_HOST: "https://bib-dev.inist.fr/api"
  VERSION_NUM: "dev"
  BIB_ENV: "-dev"
  MATOMO_SITE_ID: 86
  DOCKERFILE_DIR: "${CI_PROJECT_DIR}/packages/front"
  COMMIT_TAG: "dev-dev"
  IMAGE_NAME: "/bibcnrs/front"
  BUILD_ARGS: |
    BIBAPI_HOST=${BIBAPI_HOST}
    MATOMO_TRACKER_URL=${MATOMO_TRACKER_URL}
    MATOMO_SCRIPT_URL=${MATOMO_SCRIPT_URL}
    MATOMO_SITE_ID=${MATOMO_SITE_ID}

include:
  - project: "resinglog/ci-templates"
    file: "docker-publish.yml"

docker:publish:
  rules:
    - if: '$CI_COMMIT_BRANCH == "test"'
