services:
  bib-api:
    build:
      context: .
      dockerfile: ./ops/bib-api/Dockerfile
      target: dev
    volumes:
      - ./data/uploads:/uploads
    develop:
      watch:
        - action: sync
          path: ./packages/bib-api/src
          target: /app/packages/bib-api/src
        - action: rebuild
          path: ./packages/bib-api/prisma/schema.prisma
        - action: rebuild
          path: ./package.json
        - action: rebuild
          path: ./packages/bib-api/package.json
    depends_on:
      bib-db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://postgres:S3cr3t@bib-db/bibcnrs
      - NODE_ENV=${NODE_ENV:-development}
      - OLD_API_URL=${OLD_API_URL}
      - MAIL_SERVER_HOST=bib-mail
      - MAIL_SERVER_PORT=1025
      - cookie_secret=${cookie_secret}
      - header_secret=${header_secret}
      - admin_secret=${admin_secret}
      - BIBAPI_HOST=http://localhost:3000/api
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: ${API_MAX_MEMORY:-2G}

  bib-front:
    build:
      context: .
      dockerfile: ./ops/bib-front/Dockerfile
      target: dev
    environment:
      - NODE_ENV=development
      - VITE_ENV=development
      - VITE_BIBAPI_HOST=http://localhost:3000/api
      - VITE_SOURCE_MAP=true
    develop:
      watch:
        - action: sync
          path: ./packages/bib-front/src
          target: /app/packages/bib-front/src
        - action: sync
          path: ./packages/bib-front/public
          target: /app/packages/bib-front/public
        - action: rebuild
          path: ./package.json
        - action: rebuild
          path: ./packages/bib-front/package.json
    depends_on:
      - bib-api

  bib-admin:
    build:
      context: .
      dockerfile: ./ops/bib-admin/Dockerfile
      target: dev
    environment:
      - NODE_ENV=development
      - VITE_ENV=development
      - VITE_BIBAPI_HOST=http://localhost:3000/api
      - VITE_SOURCE_MAP=true
    develop:
      watch:
        - action: sync
          path: ./packages/bib-admin/src
          target: /app/packages/bib-admin/src
        - action: sync
          path: ./packages/bib-admin/public
          target: /app/packages/bib-admin/public
        - action: rebuild
          path: ./package.json
        - action: rebuild
          path: ./packages/bib-admin/package.json
    depends_on:
      - bib-api

  bib-proxy:
    image: nginx:1.25-alpine
    ports:
      - "3000:80"
    depends_on:
      - bib-api
      - bib-front
      - bib-admin
    develop:
      watch:
        - action: rebuild
          path:   ./ops/bib-proxy/nginx.conf
    volumes:
      - ./ops/bib-proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./data/uploads:/usr/share/nginx/html/files

  bib-db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=S3cr3t
      - POSTGRES_DB=bibcnrs
    volumes:
      - bib-db-data:/var/lib/postgresql/data
      - ./data:/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: ${API_MAX_MEMORY:-1G}

  bib-mail:
    image: maildev/maildev:2.1.0
    ports:
      - "1080:1080"
volumes:
  bib-db-data:
