services:
  bib-api:
    build:
      context: .
      dockerfile: ./ops/api/Dockerfile
    user: "${UID}:${GID}"
    ports:
      - "3001:3000"
    volumes:
      - .:/app
    working_dir: /app/packages/bib-api
    depends_on:
      bib-db:
        condition: service_healthy
    environment:
      - COREPACK_ENABLE_DOWNLOAD_PROMPT=0
      - POSTGRES_URL=postgres://bibcnrs:S3cr3t@bib-db/bibcnrs
      - NODE_ENV=${NODE_ENV:-development}
      - OLD_API_URL=${OLD_API_URL}
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: ${API_MAX_MEMORY:-2G}

  bib-db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=bibcnrs
      - POSTGRES_PASSWORD=S3cr3t
      - POSTGRES_DB=bibcnrs
    volumes:
      - bib-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: ${API_MAX_MEMORY:-1G}

  bib-front:
    user: "${UID}:${GID}"
    container_name: bib-front
    image: node:22-alpine
    environment:
      NODE_ENV: development
      VITE_ENV: development
      VITE_BIBAPI_HOST: http://localhost:3000
      VITE_SOURCE_MAP: true
    ports:
      - "5173:5173"
    volumes:
      - .:/app
    working_dir: /app/packages/bib-front
    command: yarn run dev

volumes:
  bib-db-data:
