version: "3.5"

services:
  # Application portal
  bibcnrs-front:
    image: vxnexus-registry.intra.inist.fr:8083/bibcnrs/front:${BIBFRONT_VERSION}
    container_name: bibcnrs-front
    ports:
      - "8080:8080"
    networks:
      - bib_frontend_network

  # Application back office
  bibcnrs-admin:
    image: vxnexus-registry.intra.inist.fr:8083/bibcnrs/admin:${BIBADMIN_VERSION}
    container_name: bibcnrs-admin
    ports:
      - "8081:8081"
    restart: always
    networks:
      - bib_frontend_network

  # Content delivery
  bibcnrs-content-delivery:
    container_name: bibcnrs-content-delivery
    image: nginx:1.25-alpine
    restart: always
    volumes:
      - ${CDN_CONFIG_FILE:-./../storage/nginx/content-delivery.nginx.conf}:/etc/nginx/conf.d/default.conf
      - ./../storage/uploads:/usr/share/nginx/html
    ports:
      - "8082:8082"
    networks:
      - bib_frontend_network

  # Application api
  bibcnrs-api:
    image: vxnexus-registry.intra.inist.fr:8083/bibcnrs/api:${BIBAPI_VERSION}
    container_name: bibcnrs-api
    volumes:
      - ./../storage/uploads:/app/packages/bib-api/uploads
      - ./../storage/logs:/app/packages/bib-api/logs
    environment:
      NODE_ENV: ${NODE_ENV}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      BIBAPI_HOST: ${BIBAPI_HOST}
      BIB_CONTENT_DELIVERY_HOST: ${BIB_CONTENT_DELIVERY_HOST}
      ebsco_host: ${ebsco_host}
      header_secret: ${header_secret}
      cookie_secret: ${cookie_secret}
      admin_secret: ${admin_secret}
      ticket_secret: ${ticket_secret}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      MAIL_SERVER_HOST: ${MAIL_SERVER_HOST}
      MAIL_SERVER_PORT: ${MAIL_SERVER_PORT}
      EZ_UNPAYWALL_URL: ${EZ_UNPAYWALL_URL}
      EZ_UNPAYWALL_KEY: ${EZ_UNPAYWALL_KEY}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@bibcnrs-api-postgres:5432/${POSTGRES_DB}
      METADORE_URL: ${METADORE_URL}
      METADORE_API_KEY: ${METADORE_API_KEY}
      DOAJ_URL: ${DOAJ_URL}
      # Database host is the name of the database services
      POSTGRES_HOST: bibcnrs-api-postgres
      REDIS_HOST: bibcnrs-api-redis
      OLD_API_URL: ${OLD_API_URL:-https://bib-preprod.inist.fr}
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - bibcnrs-api-redis
      - bibcnrs-api-postgres
    networks:
      - bib_backend_network
      - bib_frontend_network

  # Application database
  bibcnrs-api-postgres:
    container_name: bibcnrs-api-postgres
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./../storage/backups:/backups
      - bibcnrs-api-postgres-data:/var/lib/postgresql/data/pgdata
    ports:
      - "60000:5432"
    networks:
      - bib_backend_network

  # Cache database
  bibcnrs-api-redis:
    container_name: bibcnrs-api-redis
    image: redis:7.2.5
    restart: always
    networks:
      - bib_backend_network

volumes:
  bibcnrs-api-postgres-data:

networks:
  bib_backend_network:
    driver: bridge
    name: bib_backend_network
  bib_frontend_network:
    driver: bridge
    name: bib_frontend_network
