services:
  # Ingress
  ingress:
    image: nginx:1.27.0-alpine
    restart: always
    volumes:
      - ../storage/ingress/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/ssl/certs:/etc/ssl/certs/
      - /etc/ssl/private:/etc/ssl/private/
    ports:
      - 8443:443
    depends_on:
      - cdn
      - front
      - admin
      - api
      - shibboleth

  shibboleth:
    image: vxnexus-registry.intra.inist.fr:8083/shibboleth:latest
    environment:
      APACHE_SERVERNAME: ${APACHE_SERVERNAME}
      APACHE_SERVERADMIN: ${APACHE_SERVERADMIN}
      APACHE_LOGLEVEL: ${APACHE_LOGLEVEL}
      SHIBBOLETH_ENTITY_ID: REQUIRENOTUSED
      SHIBBOLETH_DISCOVERY_URL: REQUIRENOTUSED
    working_dir: /var/www/html
    volumes:
      - ./../storage/shibboleth/log:/var/log/shibboleth/
      - ./../storage/shibboleth/shibboleth:/etc/shibboleth/
      - ./../storage/shibboleth/apache2/sites-available:/etc/apache2/sites-available
      - /etc/ssl/certs:/etc/ssl/certs/
      - /etc/ssl/private:/etc/ssl/private/
    restart: always
    depends_on:
      - api

  # Content delivery
  cdn:
    image: nginx:1.27.0-alpine
    restart: always
    volumes:
      - ./../storage/cdn/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./../storage/uploads:/usr/share/nginx/html:ro

  # Application portal
  front:
    image: vxnexus-registry.intra.inist.fr:8083/bibcnrs/front:${BIBFRONT_VERSION}

  # Application back office
  admin:
    image: vxnexus-registry.intra.inist.fr:8083/bibcnrs/admin:${BIBADMIN_VERSION}
    restart: always

  # Application api
  api:
    image: vxnexus-registry.intra.inist.fr:8083/bibcnrs/api:${BIBAPI_VERSION}
    container_name: bibcnrs-api
    volumes:
      - ./../storage/uploads:/app/packages/api/uploads
      - ./../storage/logs:/app/packages/api/logs
    environment:
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      no_proxy: ${no_proxy}
      NODE_ENV: ${NODE_ENV}
      BIBAPI_HOST: ${BIBAPI_HOST}
      BIBFRONT_HOST: ${BIBFRONT_HOST}
      bib_admin_host: ${bib_admin_host}
      BIB_CONTENT_DELIVERY_HOST: ${BIB_CONTENT_DELIVERY_HOST}
      ebsco_host: ${ebsco_host}
      header_secret: ${header_secret}
      cookie_secret: ${cookie_secret}
      admin_secret: ${admin_secret}
      ticket_secret: ${ticket_secret}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      MAIL_SERVER_HOST: ${MAIL_SERVER_HOST}
      MAIL_SERVER_PORT: ${MAIL_SERVER_PORT}
      EZ_UNPAYWALL_URL: ${EZ_UNPAYWALL_URL}
      EZ_UNPAYWALL_KEY: ${EZ_UNPAYWALL_KEY}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      METADORE_URL: ${METADORE_URL}
      METADORE_API_KEY: ${METADORE_API_KEY}
      DOAJ_URL: ${DOAJ_URL}
      # Database host is the name of the database services
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
      MAIL_FROM: bibcnrs@bib.cnrs.fr
      MAIL_TO: assistance-portail@inist.fr
      BIB_UPLOADS_DIR: /app/packages/api/uploads
      LINKIQ_API_INP: ${LINKIQ_API_INP}
      LINKIQ_API_INSIS: ${LINKIQ_API_INSIS}
      LINKIQ_API_INSB: ${LINKIQ_API_INSB}
      LINKIQ_API_IN2P3: ${LINKIQ_API_IN2P3}
      LINKIQ_API_INSHS: ${LINKIQ_API_INSHS}
      LINKIQ_API_INSMI: ${LINKIQ_API_INSMI}
      LINKIQ_API_INS2I: ${LINKIQ_API_INS2I}
      LINKIQ_API_INEE: ${LINKIQ_API_INEE}
      LINKIQ_API_INC: ${LINKIQ_API_INC}
      LINKIQ_API_INSU: ${LINKIQ_API_INSU}
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  postgres:
    image: postgres:16.3
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
      PGUSER: ${POSTGRES_USER}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "60000:5432"
    volumes:
      - ./../storage/backups:/backups
      - ./../storage/postgresql:/var/lib/postgresql/data/pgdata

  redis:
    image: redis:7.2.5
    restart: always

  in2p3:
    image: vxnexus-registry.intra.inist.fr:8083/bibcnrs/bibezproxy:7.3.8
    container_name: bibezproxy_in2p3
    hostname: ${GATE_SUFFIX}
    restart: unless-stopped
    ports:
      - 80
      - 443
      - 2048
      - "192.168.128.201:80:80"
      - "192.168.128.201:443:443"
    env_file:
      - ./packages/ezproxy/env/env.dist
    volumes:
      - ./../storage/ezproxy/config:./config:/usr/local/ezproxy/config
      - ./../storage/ezproxy/logs:/usr/local/ezproxy/logs
  inc:
    image: vxnexus-registry.intra.inist.fr:8083/bibcnrs/bibezproxy:7.3.8
    container_name: bibezproxy_inc
    hostname: ${GATE_SUFFIX}
    restart: unless-stopped
    ports:
      - 80
      - 443
      - 2048
      - "192.168.128.202:80:80"
      - "192.168.128.202:443:443"
    env_file:
      - ./packages/ezproxy/env/env.dist
    volumes:
      - ./../storage/ezproxy/config:./config:/usr/local/ezproxy/config
      - ./../storage/ezproxy/logs:/usr/local/ezproxy/logs

  inee:
    image: vxnexus-registry.intra.inist.fr:8083/bibcnrs/bibezproxy:7.3.8
    container_name: bibezproxy_inee
    hostname: ${GATE_SUFFIX}
    restart: unless-stopped
    ports:
      - 80
      - 443
      - 2048
      - "192.168.128.203:80:80"
      - "192.168.128.203:443:443"
    env_file:
      - ./packages/ezproxy/env/env.dist
    volumes:
      - ./../storage/ezproxy/config:./config:/usr/local/ezproxy/config
      - ./../storage/ezproxy/logs:/usr/local/ezproxy/logs

  inp:
    image: vxnexus-registry.intra.inist.fr:8083/bibcnrs/bibezproxy:7.3.8
    container_name: bibezproxy_inp
    hostname: ${GATE_SUFFIX}
    restart: unless-stopped
    ports:
      - 80
      - 443
      - 2048
      - "192.168.128.204:80:80"
      - "192.168.128.204:443:443"
    env_file:
      - ./packages/ezproxy/env/env.dist
    volumes:
      - ./../storage/ezproxy/config:./config:/usr/local/ezproxy/config
      - ./../storage/ezproxy/logs:/usr/local/ezproxy/logs

  ins2i:
    image: vxnexus-registry.intra.inist.fr:8083/bibcnrs/bibezproxy:7.3.8
    container_name: bibezproxy_ins2i
    hostname: ${GATE_SUFFIX}
    restart: unless-stopped
    ports:
       - 80
       - 443
       - 2048
       - "192.168.128.205:80:80"
       - "192.168.128.205:443:443"
    env_file:
       - ./packages/ezproxy/env/env.dist
    volumes:
      - ./../storage/ezproxy/config:./config:/usr/local/ezproxy/config
      - ./../storage/ezproxy/logs:/usr/local/ezproxy/logs

  insb:
    image: vxnexus-registry.intra.inist.fr:8083/bibcnrs/bibezproxy:7.3.8
    container_name: bibezproxy_insb
    hostname: ${GATE_SUFFIX}
    restart: unless-stopped
    ports:
      - 80
      - 443
      - 2048
      - "192.168.128.206:80:80"
      - "192.168.128.206:443:443"
    env_file:
      - ./packages/ezproxy/env/env.dist
    volumes:
      - ./../storage/ezproxy/config:./config:/usr/local/ezproxy/config
      - ./../storage/ezproxy/logs:/usr/local/ezproxy/logs

  inshs:
    image: vxnexus-registry.intra.inist.fr:8083/bibcnrs/bibezproxy:7.3.8
    container_name: bibezproxy_inshs
    hostname: ${GATE_SUFFIX}
    restart: unless-stopped
    ports:
      - 80
      - 443
      - 2048
      - "192.168.128.207:80:80"
      - "192.168.128.207:443:443"
    env_file:
      - ./packages/ezproxy/env/env.dist
    volumes:
      - ./../storage/ezproxy/config:./config:/usr/local/ezproxy/config
      - ./../storage/ezproxy/logs:/usr/local/ezproxy/logs

  insis:
    image: vxnexus-registry.intra.inist.fr:8083/bibcnrs/bibezproxy:7.3.8
    container_name: bibezproxy_insis
    hostname: ${GATE_SUFFIX}
    restart: unless-stopped
    ports:
      - 80
      - 443
      - 2048
      - "192.168.128.208:80:80"
      - "192.168.128.208:443:443"
    env_file:
      - ./packages/ezproxy/env/env.dist
    volumes:
      - ./../storage/ezproxy/config:./config:/usr/local/ezproxy/config
      - ./../storage/ezproxy/logs:/usr/local/ezproxy/logs

  insmi:
    image: vxnexus-registry.intra.inist.fr:8083/bibcnrs/bibezproxy:7.3.8
    container_name: bibezproxy_insmi
    hostname: ${GATE_SUFFIX}
    restart: unless-stopped
    ports:
      - 80
      - 443
      - 2048
      - "192.168.128.208:80:80"
      - "192.168.128.208:443:443"
    env_file:
      - ./packages/ezproxy/env/env.dist
    volumes:
      - ./../storage/ezproxy/config:./config:/usr/local/ezproxy/config
      - ./../storage/ezproxy/logs:/usr/local/ezproxy/logs

  insu:
    image: vxnexus-registry.intra.inist.fr:8083/bibcnrs/bibezproxy:7.3.8
    container_name: bibezproxy_insu
    hostname: ${GATE_SUFFIX}
    restart: unless-stopped
    ports:
      - 80
      - 443
      - 2048
      - "192.168.128.209:80:80"
      - "192.168.128.209:443:443"
    env_file:
      - ./packages/ezproxy/env/env.dist
    volumes:
      - ./../storage/ezproxy/config:./config:/usr/local/ezproxy/config
      - ./../storage/ezproxy/logs:/usr/local/ezproxy/logs

