services:
  bib-api:
    build:
      context: .
      dockerfile: ./ops/api/Dockerfile
    user: '${UID}:${GID}'
    ports:
      - '3001:3000'
    volumes:
      - .:/app
    working_dir: /app/packages/bib-api
    depends_on:
      bib-db:
        condition: service_healthy
    environment:
      - COREPACK_ENABLE_DOWNLOAD_PROMPT=0
      - POSTGRES_URL=postgres://bibcnrs:S3cr3t@bib-db/bibcnrs
      - NODE_ENV=${NODE_ENV:-development}
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: ${API_MAX_MEMORY:-2G}
  bib-db:
    image: postgres:14
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=bibcnrs
      - POSTGRES_PASSWORD=S3cr3t
      - POSTGRES_DB=bibcnrs
    volumes:
      - bib-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready' ]
      interval: 10s
      timeout: 5s
      retries: 5

  ## Old Bib API services
  bib-api-old:
    build:
      context: ./packages/bib-api-old
      dockerfile: ../../ops/api-old/Dockerfile
    working_dir: /app
    environment:
      NODE_ENV: development
      BIBAPI_HOST: ${BIBAPI_HOST}
      BIB_CONTENT_DELIVERY_HOST: ${BIBAPI_HOST}/medias/
      POSTGRES_USER: bibcnrs
      POSTGRES_PASSWORD: S3cr3t
      POSTGRES_DB: bibcnrs
      POSTGRES_HOST: bib-db
      REDIS_HOST: bib-redis
      MAIL_SERVER_HOST: bib-mail
      MAIL_SERVER_PORT: 1025
      EZ_UNPAYWALL_URL: "${EZ_UNPAYWALL_URL}"
      EZ_UNPAYWALL_KEY: "${EZ_UNPAYWALL_KEY}"
      DATABASE_URL: postgres://bibcnrs:S3cr3t@bib-db/bibcnrs
      METADORE_URL: "${METADORE_URL}"
      METADORE_API_KEY: "${METADORE_API_KEY}"
      DOAJ_URL: ${DOAJ_URL}
    command: npm run dev
    depends_on:
      - bib-db
      - bib-redis
      - bib-mail

  bib-redis:
    image: redis:6.2.6

  bib-mail:
    image: maildev/maildev:2.1.0
    ports:
      - "1080:1080"
      - "1025:1025"

volumes:
  bib-db-data:
