name: 🔍 Test
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  lint:
    name: 🔬 Lint
    timeout-minutes: 10
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft || github.event_name == 'push' }}
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn

      - name: 📥 Download deps
        run: make install-immutable

      - name: 🔎 Lint check
        run: make lint-check

  typecheck:
    name: ʦ TypeScript
    timeout-minutes: 10
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft || github.event_name == 'push' }}
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn

      - name: 📥 Download deps
        run: make install-immutable

      - name: 🔎 Type check
        run: make typecheck

  test:
    name: 🔎 Test
    timeout-minutes: 10
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft || github.event_name == 'push' }}
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: 🔎 Test API
        run: make test-api
